version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.0
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m -Xms2600m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2/
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew build
      - store_artifacts:
          path: deluxemediaplugin/build/libs/DeluxeMediaPlugin-all.jar
workflows:
  version: 2
  build-deps-and-compile:
    jobs:
      - build:
          requires:
            - BUILDTOOLS
            - JAVA-16-NMS
            - JAVA-17-NMS
      - BUILDTOOLS:
          docker:
            - image: cimg/openjdk:16.0.1
          working_directory: ~/repo
          steps:
            - checkout
            - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - JAVA-16-NMS:
          docker:
            - image: cimg/openjdk:16.0.1
          working_directory: ~/repo
          steps:
            - checkout
            - run: java -jar BuildTools.jar --rev 1.16.5
            - run: java -jar BuildTools.jar --rev 1.17.1
      - JAVA-17-NMS:
          docker:
            - image: cimg/openjdk:17.0.0
          working_directory: ~/repo
          steps:
            - checkout
            - run: java -jar BuildTools.jar --rev 1.18.1
